### ISSUE TITLE
To-do list 

### ISSUE THREAD

**Issue by zeyaoli** [Cybernetics-of-Sex/CyberneticsofSex#3]
- [x] Click empty space to close info box
- [x] Remove img tag if there's no image displayed 
- [ ] Polish CSS a bit more
